import { useState } from 'react';
import { useParams } from 'wouter';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@complianceos/ui/ui/card';
import { Button } from '@complianceos/ui/ui/button';
import { Badge } from '@complianceos/ui/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@complianceos/ui/ui/tabs';
import { Shield, AlertTriangle, Activity, Server, Search, RefreshCw, ExternalLink, CheckCircle, XCircle, Clock } from 'lucide-react';
import DashboardLayout from '@/components/DashboardLayout';
import { PageGuide } from '@/components/PageGuide';
import { Breadcrumb } from '@/components/Breadcrumb';

const mockAlerts = [
    { id: 'SIEM-001', title: 'Brute Force Attack Detected', severity: 'high', source: 'Firewall', timestamp: '2026-02-24T14:30:00Z', status: 'open' },
    { id: 'SIEM-002', title: 'Suspicious PowerShell Execution', severity: 'critical', source: 'EDR', timestamp: '2026-02-24T13:45:00Z', status: 'open' },
    { id: 'SIEM-003', title: 'Failed Login Attempts', severity: 'medium', source: 'AD', timestamp: '2026-02-24T12:00:00Z', status: 'investigating' },
    { id: 'SIEM-004', title: 'Malware Detected - Trojan', severity: 'critical', source: 'Antivirus', timestamp: '2026-02-23T22:15:00Z', status: 'contained' },
    { id: 'SIEM-005', title: 'Data Exfiltration Pattern', severity: 'high', source: 'DLP', timestamp: '2026-02-23T18:30:00Z', status: 'open' },
    { id: 'SIEM-006', title: 'Privilege Escalation', severity: 'high', source: 'AD Security', timestamp: '2026-02-23T15:20:00Z', status: 'resolved' }
];

const mockIncidents = [
    { id: 'INC-001', title: 'Active Intrusion Attempt', severity: 'critical', status: 'open', assignee: 'Security Team', created: '2026-02-24T14:30:00Z' },
    { id: 'INC-002', title: 'Data Leak Investigation', severity: 'high', status: 'investigating', assignee: 'DLP Team', created: '2026-02-23T18:30:00Z' },
    { id: 'INC-003', title: 'Unauthorized Access', severity: 'medium', status: 'resolved', assignee: 'Jane Doe', created: '2026-02-24T08:30:00Z' }
];

const severityColors: Record<string, string> = {
    critical: 'bg-red-100 text-red-800',
    high: 'bg-orange-100 text-orange-800',
    medium: 'bg-yellow-100 text-yellow-800',
    low: 'bg-blue-100 text-blue-800'
};

export default function SIEMDashboard() {
    const params = useParams();
    const clientId = params.id;

    return (
        <DashboardLayout>
            <div className="p-6">
                <div className="max-w-7xl mx-auto">
                    <div className="flex items-center justify-between mb-8">
                        <Breadcrumb items={[{ label: "Cyber Resilience", href: `/clients/${clientId}/cyber` }, { label: "SIEM" }]} />
                        <div className="flex gap-3">
                            <PageGuide
                                title="SIEM Dashboard"
                                description="Real-time analysis of security alerts generated by applications and network hardware."
                                rationale="A SIEM provides a holistic view of an organization's security posture by aggregating log data from multiple sources and identifying patterns that indicate threat activity."
                                howToUse={[
                                    {
                                        step: "Monitor Alerts",
                                        description: "Review the security alerts feed to identify potential threats in real-time.",
                                        targetId: "siem-tabs-list"
                                    },
                                    {
                                        step: "Search Logs",
                                        description: "Perform ad-hoc queries across your organization's logs.",
                                        targetId: "siem-search-btn"
                                    },
                                    {
                                        step: "Sync Alerts",
                                        description: "Manually trigger a synchronization to pull the latest alerts from your SIEM providers.",
                                        targetId: "siem-sync-btn"
                                    },
                                    {
                                        step: "Track Metrics",
                                        description: "Monitor critical alert volume and incident resolution trends.",
                                        targetId: "siem-metrics-grid"
                                    }
                                ]}
                                scenarios={[
                                    {
                                        title: "Suspicious Login Spike",
                                        example: "A sudden spike in failed login attempts for a specific account. Use SIEM logs to identify the source IP and verify if it's a brute force attack.",
                                        auditTip: "Auditors look for 'Alert Triage'—ensure that any 'Critical' or 'High' alerts have associated investigation notes or incidents."
                                    },
                                    {
                                        title: "Unauthorized IP Connection",
                                        example: "An internal server attempts to connect to a known malicious IP address. Trace the process responsible for the connection.",
                                        auditTip: "Maintain a clear 'Correlation Rule' documentation to show auditors how your SIEM automatically identifies complex attack patterns."
                                    }
                                ]}
                                integrations={[
                                    { name: "SOAR Automation", description: "SIEM alerts can trigger automated playbooks in the SOAR module." },
                                    { name: "Threat Intel", description: "Logs are automatically cross-referenced with your threat intelligence feeds." }
                                ]}
                            />
                            <Button id="siem-search-btn" variant="outline" className="border-slate-300 text-slate-700 hover:bg-slate-100">
                                <Search className="h-4 w-4 mr-2" />
                                Search Logs
                            </Button>
                            <Button id="siem-sync-btn" className="bg-blue-600 hover:bg-blue-700">
                                <RefreshCw className="h-4 w-4 mr-2" />
                                Sync Alerts
                            </Button>
                        </div>
                    </div>

                    <div id="siem-metrics-grid" className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
                        <Card className="bg-white border-slate-200">
                            <CardContent className="pt-6">
                                <div className="flex items-center justify-between">
                                    <div>
                                        <p className="text-slate-500 text-sm">Total Alerts</p>
                                        <p className="text-3xl font-bold text-slate-900">{mockAlerts.length}</p>
                                    </div>
                                    <AlertTriangle className="h-8 w-8 text-orange-500" />
                                </div>
                            </CardContent>
                        </Card>
                        <Card className="bg-white border-slate-200">
                            <CardContent className="pt-6">
                                <div className="flex items-center justify-between">
                                    <div>
                                        <p className="text-slate-500 text-sm">Critical</p>
                                        <p className="text-3xl font-bold text-red-600">{mockAlerts.filter(a => a.severity === 'critical').length}</p>
                                    </div>
                                    <XCircle className="h-8 w-8 text-red-500" />
                                </div>
                            </CardContent>
                        </Card>
                        <Card className="bg-white border-slate-200">
                            <CardContent className="pt-6">
                                <div className="flex items-center justify-between">
                                    <div>
                                        <p className="text-slate-500 text-sm">Open Incidents</p>
                                        <p className="text-3xl font-bold text-orange-600">{mockIncidents.filter(i => i.status === 'open').length}</p>
                                    </div>
                                    <Activity className="h-8 w-8 text-orange-500" />
                                </div>
                            </CardContent>
                        </Card>
                        <Card className="bg-white border-slate-200">
                            <CardContent className="pt-6">
                                <div className="flex items-center justify-between">
                                    <div>
                                        <p className="text-slate-500 text-sm">Resolved Today</p>
                                        <p className="text-3xl font-bold text-green-600">12</p>
                                    </div>
                                    <CheckCircle className="h-8 w-8 text-green-500" />
                                </div>
                            </CardContent>
                        </Card>
                    </div>

                    <Tabs defaultValue="alerts" className="space-y-4">
                        <TabsList id="siem-tabs-list" className="bg-white border-slate-200">
                            <TabsTrigger value="alerts" className="data-[state=active]:bg-blue-600">Security Alerts</TabsTrigger>
                            <TabsTrigger value="incidents" className="data-[state=active]:bg-blue-600">Incidents</TabsTrigger>
                            <TabsTrigger value="dashboards" className="data-[state=active]:bg-blue-600">Dashboards</TabsTrigger>
                        </TabsList>

                        <TabsContent value="alerts">
                            <Card className="bg-white border-slate-200">
                                <CardHeader>
                                    <CardTitle>Security Alerts</CardTitle>
                                    <CardDescription>Recent security alerts from your SIEM</CardDescription>
                                </CardHeader>
                                <CardContent>
                                    <div className="space-y-3">
                                        {mockAlerts.map((alert) => (
                                            <div key={alert.id} className="flex items-center justify-between p-4 bg-slate-50 rounded-lg border border-slate-100">
                                                <div className="flex items-center gap-4">
                                                    <Badge className={severityColors[alert.severity]}>{alert.severity}</Badge>
                                                    <div>
                                                        <p className="font-semibold text-slate-900">{alert.title}</p>
                                                        <p className="text-sm text-slate-500">{alert.source} • {alert.timestamp}</p>
                                                    </div>
                                                </div>
                                                <div className="flex items-center gap-2">
                                                    <span className={`px-2 py-1 text-xs rounded ${alert.status === 'open' ? 'bg-red-100 text-red-700' :
                                                        alert.status === 'investigating' ? 'bg-yellow-100 text-yellow-700' :
                                                            'bg-green-100 text-green-700'
                                                        }`}>
                                                        {alert.status}
                                                    </span>
                                                    <Button variant="ghost" size="sm">
                                                        <ExternalLink className="h-4 w-4" />
                                                    </Button>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </CardContent>
                            </Card>
                        </TabsContent>

                        <TabsContent value="incidents">
                            <Card className="bg-white border-slate-200">
                                <CardHeader>
                                    <CardTitle>Security Incidents</CardTitle>
                                    <CardDescription>Active and recent security incidents</CardDescription>
                                </CardHeader>
                                <CardContent>
                                    <div className="space-y-3">
                                        {mockIncidents.map((incident) => (
                                            <div key={incident.id} className="flex items-center justify-between p-4 bg-slate-50 rounded-lg border border-slate-100">
                                                <div className="flex items-center gap-4">
                                                    <Badge className={severityColors[incident.severity]}>{incident.severity}</Badge>
                                                    <div>
                                                        <p className="font-semibold text-slate-900">{incident.title}</p>
                                                        <p className="text-sm text-slate-500">{incident.assignee} • {incident.created}</p>
                                                    </div>
                                                </div>
                                                <div className="flex items-center gap-2">
                                                    <span className={`px-2 py-1 text-xs rounded ${incident.status === 'open' ? 'bg-red-100 text-red-700' :
                                                        incident.status === 'investigating' ? 'bg-yellow-100 text-yellow-700' :
                                                            'bg-green-100 text-green-700'
                                                        }`}>
                                                        {incident.status}
                                                    </span>
                                                    <Button variant="ghost" size="sm">
                                                        <ExternalLink className="h-4 w-4" />
                                                    </Button>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </CardContent>
                            </Card>
                        </TabsContent>

                        <TabsContent value="dashboards">
                            <Card className="bg-white border-slate-200">
                                <CardHeader>
                                    <CardTitle>SIEM Dashboards</CardTitle>
                                    <CardDescription>Available security dashboards</CardDescription>
                                </CardHeader>
                                <CardContent>
                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                        {['Threat Overview', 'Network Security', 'Endpoint Security'].map((name) => (
                                            <div key={name} className="p-6 bg-slate-50 rounded-lg border border-slate-100 hover:bg-slate-100 cursor-pointer transition-colors">
                                                <div className="flex items-center gap-3 mb-2">
                                                    <Server className="h-5 w-5 text-blue-600" />
                                                    <h3 className="font-semibold text-slate-900">{name}</h3>
                                                </div>
                                                <p className="text-sm text-slate-500">Click to view dashboard</p>
                                            </div>
                                        ))}
                                    </div>
                                </CardContent>
                            </Card>
                        </TabsContent>
                    </Tabs>
                </div>
            </div>
        </DashboardLayout>
    );
}
