
import 'dotenv/config';
import { getDb } from '../src/db';
import { readinessAssessments } from '../src/schema'; // Relative to scripts/
import { eq, and } from 'drizzle-orm';

async function main() {
    try {
        const db = await getDb();
        const clientId = 3;
        const standardId = "SOC2"; // Normalized ID

        console.log(`🚀 Seeding SOC 2 Readiness for Client ${clientId}...`);

        const existing = await db.select().from(readinessAssessments).where(
            and(
                eq(readinessAssessments.clientId, clientId),
                eq(readinessAssessments.standardId, standardId)
            )
        );

        const mockData = {
            scopeDetails: {
                orgBoundaries: "Acme Corp (Client 3) - Global Operations",
                locations: "HQ (San Francisco), Data Centers (us-east-1, eu-west-1), Remote Employees",
                technologies: "AWS, Kubernetes, Github, Slack, Jira, Salesforce, Okta"
            },
            stakeholders: {
                securityLead: "Sarah Connor (CISO)",
                executiveSponsor: "Miles Dyson (CTO)",
                itLead: "John Henry (VP Infra)"
            },
            existingPolicies: {
                "accessControl": true,
                "incidentResponse": true,
                "dataClassification": true,
                "vendorManagement": true,
                "changeManagement": false,
                "businessContinuity": false
            },
            businessContext: {
                criticalAssets: "Customer Data, Source Code, Production Infrastructure keys",
                legalRequirements: "SOC 2 Type 2, GDPR, HIPAA (future date)",
                riskAppetite: "Low tolerance for availability risks, moderate for operational risks."
            },
            maturityExpectations: {
                targetMaturity: "Optimized (Level 4)",
                primaryObjective: "SOC 2 Type 2 Report for Enterprise Sales",
                timeline: "Q3 2026"
            },
            scopingReport: `# Executive Scoping Report: SOC 2 Readiness
**Date:** ${new Date().toLocaleDateString()}
**Generated By:** ComplianceOS AI

## Executive Summary
Acme Corp is strictly targeting a SOC 2 Type 2 attestation to unblock enterprise sales channels. The scope is well-defined around the core SaaS platform hosted in AWS.

## Scope Definitions
- **Boundaries:** All global operations affecting the "ComplianceOS" product.
- **Excluded:** Legacy on-premise verification systems (sunset planned Q4).
- **Locations:** San Francisco HQ and Remote endpoints.

## Governance & Stakeholders
Confirmed leadership buy-in from CTO Miles Dyson. CISO Sarah Connor will lead the daily implementation.

## Key Findings & Maturity
- **Strengths:** Strong access control and incident response foundations.
- **Gaps:** Change management documentation is informal. Business Continuity Plan (BCP) is untested.
- **Target:** achieving "Optimized" maturity by Q3 2026.

## Next Steps
1. Formalize Change Management Policy.
2. Conduct BCP Tabletop exercise.
3. Begin control mapping for "Common Criteria" and "Availability" trust services criteria.
`
        };

        if (existing.length > 0) {
            console.log("ℹ️ Updating existing assessment...");
            await db.update(readinessAssessments).set({
                ...mockData,
                currentStep: 6,
                status: "in_progress",
                updatedAt: new Date()
            }).where(eq(readinessAssessments.id, existing[0].id));
        } else {
            console.log("✨ Creating new assessment...");
            await db.insert(readinessAssessments).values({
                clientId,
                standardId,
                name: "SOC 2 Readiness - 2026",
                currentStep: 6,
                status: "in_progress",
                ...mockData,
                createdAt: new Date(),
                updatedAt: new Date()
            });
        }

        console.log("✅ SOC 2 Seeding Complete for Client 3.");

    } catch (e) {
        console.error("❌ Seeding failed:", e);
        process.exit(1);
    }
    process.exit(0);
}

main();
