
import {
    Document,
    Packer,
    Paragraph,
    TextRun,
    HeadingLevel,
    AlignmentType,
    Header,
    Footer,
    PageNumber,
    VerticalAlign,
    Table,
    TableRow,
    TableCell,
    WidthType,
    BorderStyle,
    ShadingType,
    PageBreak,
    convertInchesToTwip,
    LevelFormat,
} from "docx";

// Reuse brand colors from policyExportProfessional
const BRAND_PRIMARY = "0F172A";
const BRAND_TEXT = "334155";
const BRAND_BORDER = "E2E8F0";

// Interface for SoA Data
export interface SoAExportData {
    clientName: string;
    generatedDate: Date;
    controls: {
        code: string | null;
        name: string;
        framework: string;
        applicability: string;
        justification: string;
        status: string;
        implementationDate?: Date | null;
    }[];
}

export async function generateSoADocx(data: SoAExportData): Promise<Buffer> {
    const doc = new Document({
        sections: [
            {
                properties: {
                    page: {
                        margin: {
                            top: convertInchesToTwip(1),
                            right: convertInchesToTwip(1),
                            bottom: convertInchesToTwip(1),
                            left: convertInchesToTwip(1),
                        },
                    },
                },
                headers: {
                    default: new Header({
                        children: [
                            new Paragraph({
                                children: [
                                    new TextRun({ text: "Statement of Applicability (SoA)", bold: true, size: 24 }),
                                    new TextRun({ text: ` | ${data.clientName}`, size: 24, color: "777777" }),
                                ],
                                alignment: AlignmentType.RIGHT,
                            }),
                        ],
                    }),
                },
                footers: {
                    default: new Footer({
                        children: [
                            new Paragraph({
                                children: [
                                    new TextRun("Generated by ComplianceOS"),
                                    new TextRun({ children: [PageNumber.CURRENT, " / ", PageNumber.TOTAL_PAGES] }),
                                ],
                                alignment: AlignmentType.CENTER,
                            })
                        ]
                    })
                },
                children: [
                    // Title
                    new Paragraph({
                        text: "Statement of Applicability",
                        heading: HeadingLevel.HEADING_1,
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 400 },
                    }),

                    new Paragraph({
                        text: `This document defines the applicability of information security controls for ${data.clientName}.`,
                        spacing: { after: 400 },
                    }),

                    // SoA Table
                    new Table({
                        width: { size: 100, type: WidthType.PERCENTAGE },
                        rows: [
                            // Header Row
                            new TableRow({
                                tableHeader: true,
                                children: [
                                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Control", bold: true })] })], width: { size: 15, type: WidthType.PERCENTAGE }, shading: { fill: "F8FAFC" } }),
                                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Description", bold: true })] })], width: { size: 35, type: WidthType.PERCENTAGE }, shading: { fill: "F8FAFC" } }),
                                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Applicability", bold: true })] })], width: { size: 15, type: WidthType.PERCENTAGE }, shading: { fill: "F8FAFC" } }),
                                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Justification", bold: true })] })], width: { size: 35, type: WidthType.PERCENTAGE }, shading: { fill: "F8FAFC" } }),
                                ],
                            }),
                            // Data Rows
                            ...data.controls.map(control => new TableRow({
                                children: [
                                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: control.code || "", bold: true })] })] }),
                                    new TableCell({ children: [new Paragraph({ children: [new TextRun(control.name)] })] }),
                                    new TableCell({
                                        children: [new Paragraph({
                                            children: [new TextRun({
                                                text: control.applicability === 'not_applicable' ? "Excluded" : "Included",
                                                color: control.applicability === 'not_applicable' ? "999999" : "000000"
                                            })]
                                        })]
                                    }),
                                    new TableCell({ children: [new Paragraph({ children: [new TextRun(control.justification || "-")] })] }),
                                ]
                            }))
                        ],
                    }),
                ],
            },
        ],
    });

    return Packer.toBuffer(doc);
}
